version: "1"
services:
  deployment:
    image: calculator-app:$VERSION
    build:
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      PORT: 5001
      AUTHOR: "Christopher Le"
      
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - deployment