version: "1"
services:
  deployment:
    image: rest-api:${VERSION}
    build:
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      PORT: 5001
      AUTHOR: "Christopher Le"

  load_balancer: 
    image: nginx:1.25.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - deployment